name: iremember
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.3+4
  firebase_storage: ^2.1.0+1
  firebase_auth: ^0.8.3
  geolocator: 5.0.1
  uuid: ^2.0.0
  image: ^2.0.7
  cupertino_icons: ^0.1.2
  path_provider: ^1.4.0
  timeago: 2.0.17
  cached_network_image:
  flutter_svg:
  google_fonts: ^0.2.0
  cloud_firestore: ^0.9.7+2
  google_sign_in: ^4.0.1+1
  curved_navigation_bar: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg

    
    
                                      